/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/public/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/auth/passwordreset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset email */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/auth/passwordchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password using reset token */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/extendtoken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend JWT token lifetime */
        post: operations["extendToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validate/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate email address with code */
        post: operations["validateEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/validationrequest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-send validation email */
        post: operations["validationRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update user profile (name) */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user */
        get: operations["getUser"];
        /** Update user */
        put: operations["updateUser"];
        post?: never;
        /** Delete user account */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available payment methods */
        get: operations["listPaymentMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/idealissuers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List iDEAL issuers */
        get: operations["listIDealIssuers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/buycredits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purchase credits */
        post: operations["buyCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/tournaments/{tournamentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public tournament */
        get: operations["getPublicTournament"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/tournaments/{tournamentId}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public tournament structure */
        get: operations["getPublicStructure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/tournaments/{tournamentId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public tournament rules */
        get: operations["getPublicRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/tournaments/{tournamentId}/registrations/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public registration settings */
        get: operations["getPublicRegistrationSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/tournaments/{tournamentId}/categories/{categoryId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a public registration */
        post: operations["addPublicRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create tournament */
        post: operations["createTournament"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tournament (authenticated) */
        get: operations["getTournament"];
        /** Update tournament */
        put: operations["updateTournament"];
        post?: never;
        /** Delete tournament */
        delete: operations["deleteTournament"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/competitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List competitors */
        get: operations["listCompetitors"];
        put?: never;
        /** Add competitor */
        post: operations["addCompetitor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/competitors/{competitorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get competitor */
        get: operations["getCompetitor"];
        /** Update competitor */
        put: operations["updateCompetitor"];
        post?: never;
        /** Remove competitor */
        delete: operations["deleteCompetitor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/competitors/{competitorOneId}/{competitorTwoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Swap two competitors */
        put: operations["swapCompetitors"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/sponsors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sponsors */
        get: operations["listSponsors"];
        put?: never;
        /** Add sponsor */
        post: operations["addSponsor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/sponsors/{sponsorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update sponsor */
        put: operations["updateSponsor"];
        post?: never;
        /** Remove sponsor */
        delete: operations["deleteSponsor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/lockerrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add locker room */
        post: operations["addLockerRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/lockerrooms/{lockerRoomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update locker room */
        put: operations["updateLockerRoom"];
        post?: never;
        /** Remove locker room */
        delete: operations["deleteLockerRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/lockerrooms/{lockerRoomId}/synccompetitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync competitors assigned to locker room */
        post: operations["syncLockerRoomCompetitors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/recesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add recess */
        post: operations["addRecess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/recesses/{recessId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove recess */
        delete: operations["deleteRecess"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rules */
        get: operations["listRules"];
        put?: never;
        /** Add rule */
        post: operations["addRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update rule */
        put: operations["updateRule"];
        post?: never;
        /** Remove rule */
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/rules/{ruleId}/priorityup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move rule up in priority */
        post: operations["rulesPriorityUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/users/{tournamentUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove user from tournament */
        delete: operations["removeTournamentUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/users/{tournamentUserId}/emailaddress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get email address of tournament user */
        get: operations["getTournamentUserEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/users/{tournamentUserId}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add role to tournament user */
        post: operations["addTournamentUserRole"];
        /** Remove role from tournament user */
        delete: operations["removeTournamentUserRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invitations */
        get: operations["listInvitations"];
        put?: never;
        /** Send invitation */
        post: operations["addInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke invitation */
        delete: operations["deleteInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/invitations/{invitationId}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add role to invitation */
        post: operations["addInvitationRole"];
        /** Remove role from invitation */
        delete: operations["removeInvitationRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/categories/{categoryId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registrations for a category */
        get: operations["listRegistrations"];
        put?: never;
        /** Add registration (admin) */
        post: operations["addRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/categories/{categoryId}/registrations/{registrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get registration */
        get: operations["getRegistration"];
        /** Update registration (accept / decline) */
        put: operations["updateRegistration"];
        post?: never;
        /** Delete registration */
        delete: operations["deleteRegistration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/registrations/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get registration settings */
        get: operations["getRegistrationSettings"];
        /** Update registration settings */
        put: operations["updateRegistrationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            emailaddress: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            emailaddress: string;
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: email */
            emailaddress: string;
            password: string;
            token: string;
        };
        TokenResponse: {
            token?: string;
            userId?: number;
        };
        User: {
            id?: number;
            /** Format: email */
            emailaddress?: string;
            name?: string | null;
            validated?: boolean;
            nrOfCredits?: number;
        };
        UserUpdateRequest: {
            /** Format: email */
            emailaddress?: string;
            name?: string | null;
        };
        Tournament: {
            id?: number;
            /** Format: date-time */
            createdDateTime?: string;
            /** @enum {string} */
            startEditMode?: "EditMode" | "ReadMode";
            public?: boolean;
            example?: boolean;
            intro?: string;
            location?: string | null;
            logoExtension?: string | null;
            theme?: {
                [key: string]: unknown;
            } | null;
        };
        TournamentRequest: {
            intro: string;
            location?: string | null;
            public?: boolean;
            theme?: {
                [key: string]: unknown;
            } | null;
        };
        Competitor: {
            id?: number;
            name?: string;
            present?: boolean;
            logoExtension?: string | null;
            publicInfo?: string | null;
            privateInfo?: string | null;
            /** Format: email */
            emailaddress?: string | null;
            telephone?: string | null;
        };
        CompetitorRequest: {
            name: string;
            present?: boolean;
            publicInfo?: string | null;
            privateInfo?: string | null;
            /** Format: email */
            emailaddress?: string | null;
            telephone?: string | null;
        };
        Sponsor: {
            id?: number;
            name?: string;
            url?: string | null;
            logoExtension?: string | null;
            /** @default 1 */
            screenNr: number;
        };
        SponsorRequest: {
            name: string;
            url?: string | null;
            /** @default 1 */
            screenNr: number;
        };
        LockerRoom: {
            id?: number;
            name?: string;
            /** @description Competitor IDs assigned to this locker room. */
            competitors?: number[];
        };
        LockerRoomRequest: {
            name: string;
        };
        Recess: {
            id?: number;
            name?: string;
            /** Format: date-time */
            startDateTime?: string;
            /** Format: date-time */
            endDateTime?: string;
        };
        RecessRequest: {
            name: string;
            /** Format: date-time */
            startDateTime: string;
            /** Format: date-time */
            endDateTime: string;
        };
        Rule: {
            id?: number;
            text?: string;
            priority?: number;
        };
        RuleRequest: {
            text: string;
        };
        TournamentUser: {
            id?: number;
            userId?: number;
            /** @description Bitmask of roles. */
            roles?: number;
        };
        Invitation: {
            id?: number;
            /** Format: email */
            emailaddress?: string;
            /** @description Bitmask of roles. */
            roles?: number;
            /** Format: date-time */
            createdDateTime?: string;
        };
        InvitationRequest: {
            /** Format: email */
            emailaddress: string;
            roles: number;
        };
        Registration: {
            id?: number;
            categoryNr?: number;
            name?: string;
            /** Format: email */
            emailaddress?: string;
            telephone?: string;
            info?: string | null;
            /** @enum {string} */
            state?: "Pending" | "Accepted" | "Declined";
            competitorId?: number | null;
        };
        RegistrationRequest: {
            name: string;
            /** Format: email */
            emailaddress: string;
            telephone: string;
            info?: string | null;
        };
        RegistrationUpdateRequest: {
            /** @enum {string} */
            state?: "Pending" | "Accepted" | "Declined";
            competitorId?: number | null;
        };
        RegistrationSettings: {
            id?: number;
            enabled?: boolean;
            /** Format: date-time */
            endDateTime?: string;
            remark?: string | null;
            mailAlert?: boolean;
            acceptText?: string | null;
            acceptAsSubstituteText?: string | null;
            declineText?: string | null;
        };
        RegistrationSettingsRequest: {
            enabled: boolean;
            /** Format: date-time */
            endDateTime: string;
            remark?: string | null;
            mailAlert: boolean;
            acceptText?: string | null;
            acceptAsSubstituteText?: string | null;
            declineText?: string | null;
        };
        Payment: {
            id?: number;
            paymentId?: string | null;
            method?: string;
            /** Format: decimal */
            amount?: number;
            /** @enum {string} */
            state?: "Open" | "Pending" | "Authorized" | "Expired" | "Failed" | "Canceled" | "Paid";
            /** Format: date-time */
            updatedAt?: string;
        };
        BuyCreditsRequest: {
            method: string;
            /** Format: decimal */
            amount: number;
            /** @description Required for iDEAL payments. */
            issuer?: string | null;
        };
        IDealIssuer: {
            id?: string;
            name?: string;
        };
    };
    responses: {
        /** @description Invalid request payload. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Missing or invalid authentication. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Insufficient permissions. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        userId: number;
        tournamentId: number;
        competitorId: number;
        sponsorId: number;
        lockerRoomId: number;
        recessId: number;
        ruleId: number;
        tournamentUserId: number;
        invitationId: number;
        categoryId: number;
        registrationId: number;
        paymentId: string;
        code: string;
        role: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Email address already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description JWT token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    emailaddress: string;
                };
            };
        };
        responses: {
            /** @description Reset email sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    extendToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New JWT token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    validateEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["code"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email validated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    validationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation email sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Profile updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description User updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["userId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listPaymentMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment methods. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    listIDealIssuers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description iDEAL issuers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IDealIssuer"][];
                };
            };
        };
    };
    buyCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyCreditsRequest"];
            };
        };
        responses: {
            /** @description Payment initiated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["paymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPublicTournament: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPublicStructure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament structure (JSON). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    getPublicRegistrationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSettings"];
                };
            };
        };
    };
    addPublicRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                categoryId: components["parameters"]["categoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Registration submitted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createTournament: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentRequest"];
            };
        };
        responses: {
            /** @description Tournament created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getTournament: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTournament: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentRequest"];
            };
        };
        responses: {
            /** @description Tournament updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    deleteTournament: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listCompetitors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competitors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competitor"][];
                };
            };
        };
    };
    addCompetitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitorRequest"];
            };
        };
        responses: {
            /** @description Competitor added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competitor"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCompetitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                competitorId: components["parameters"]["competitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competitor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competitor"];
                };
            };
        };
    };
    updateCompetitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                competitorId: components["parameters"]["competitorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitorRequest"];
            };
        };
        responses: {
            /** @description Competitor updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competitor"];
                };
            };
        };
    };
    deleteCompetitor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                competitorId: components["parameters"]["competitorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competitor removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    swapCompetitors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                competitorOneId: number;
                competitorTwoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competitors swapped. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSponsors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sponsors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sponsor"][];
                };
            };
        };
    };
    addSponsor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SponsorRequest"];
            };
        };
        responses: {
            /** @description Sponsor added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sponsor"];
                };
            };
        };
    };
    updateSponsor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                sponsorId: components["parameters"]["sponsorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SponsorRequest"];
            };
        };
        responses: {
            /** @description Sponsor updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sponsor"];
                };
            };
        };
    };
    deleteSponsor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                sponsorId: components["parameters"]["sponsorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sponsor removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addLockerRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockerRoomRequest"];
            };
        };
        responses: {
            /** @description Locker room added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockerRoom"];
                };
            };
        };
    };
    updateLockerRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                lockerRoomId: components["parameters"]["lockerRoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockerRoomRequest"];
            };
        };
        responses: {
            /** @description Locker room updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockerRoom"];
                };
            };
        };
    };
    deleteLockerRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                lockerRoomId: components["parameters"]["lockerRoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Locker room removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncLockerRoomCompetitors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                lockerRoomId: components["parameters"]["lockerRoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    competitorIds?: number[];
                };
            };
        };
        responses: {
            /** @description Competitors synced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addRecess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecessRequest"];
            };
        };
        responses: {
            /** @description Recess added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recess"];
                };
            };
        };
    };
    deleteRecess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                recessId: components["parameters"]["recessId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recess removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    addRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRequest"];
            };
        };
        responses: {
            /** @description Rule added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                ruleId: components["parameters"]["ruleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleRequest"];
            };
        };
        responses: {
            /** @description Rule updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                ruleId: components["parameters"]["ruleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rulesPriorityUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                ruleId: components["parameters"]["ruleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Priority updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeTournamentUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                tournamentUserId: components["parameters"]["tournamentUserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTournamentUserEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                tournamentUserId: components["parameters"]["tournamentUserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email address. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: email */
                        emailaddress?: string;
                    };
                };
            };
        };
    };
    addTournamentUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                tournamentUserId: components["parameters"]["tournamentUserId"];
                role: components["parameters"]["role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role added. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeTournamentUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                tournamentUserId: components["parameters"]["tournamentUserId"];
                role: components["parameters"]["role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"][];
                };
            };
        };
    };
    addInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation sent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
        };
    };
    deleteInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                invitationId: components["parameters"]["invitationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addInvitationRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                invitationId: components["parameters"]["invitationId"];
                role: components["parameters"]["role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role added. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeInvitationRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                invitationId: components["parameters"]["invitationId"];
                role: components["parameters"]["role"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                categoryId: components["parameters"]["categoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registrations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"][];
                };
            };
        };
    };
    addRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                categoryId: components["parameters"]["categoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Registration added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
        };
    };
    getRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                categoryId: components["parameters"]["categoryId"];
                registrationId: components["parameters"]["registrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
        };
    };
    updateRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                categoryId: components["parameters"]["categoryId"];
                registrationId: components["parameters"]["registrationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationUpdateRequest"];
            };
        };
        responses: {
            /** @description Registration updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
        };
    };
    deleteRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
                categoryId: components["parameters"]["categoryId"];
                registrationId: components["parameters"]["registrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRegistrationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSettings"];
                };
            };
        };
    };
    updateRegistrationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: components["parameters"]["tournamentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationSettingsRequest"];
            };
        };
        responses: {
            /** @description Settings updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSettings"];
                };
            };
        };
    };
}
