name: Deploy to Azure

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-dev:
    if: github.event_name == 'push'
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: dev
      resource-group: rg-fctoernooi-dev
      core-resource-group: rg-core-dev
    secrets: inherit

  deploy-acc:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: acc
      resource-group: rg-fctoernooi-acc
      core-resource-group: rg-core-acc
    secrets: inherit

  deploy-prd:
    needs: deploy-acc
    uses: ./.github/workflows/_deploy-env.yml
    with:
      environment: prd
      resource-group: rg-fctoernooi-prd
      core-resource-group: rg-core-prd
    secrets: inherit


